# Generated by Django 2.2.6 on 2019-10-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191021_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='content',
            name='reviews_total',
        ),
    ]
