# Generated by Django 2.2.6 on 2019-10-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191021_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='reviews_total',
            field=models.IntegerField(default=0),
        ),
    ]
