# Generated by Django 2.2.6 on 2019-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_reviews_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
