# Generated by Django 2.0.2 on 2019-10-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_review_readability_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='readability_comments',
            new_name='readability',
        ),
    ]
