# Generated by Django 2.0.2 on 2019-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20191030_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='readability_rating',
            field=models.IntegerField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], default=0),
        ),
    ]
