# Generated by Django 2.0.2 on 2019-11-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_review_readability_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='readability_rating',
        ),
    ]
