# Generated by Django 2.0.2 on 2019-11-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_review_readability_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='readability_rating',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
