# Generated by Django 2.0.2 on 2019-11-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_review_readability_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actionability',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='actionability_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='general_comments',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='readability_rating',
            field=models.IntegerField(),
        ),
    ]
