# Generated by Django 2.0.2 on 2019-11-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20191104_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='reviews_total',
        ),
    ]
