# Generated by Django 2.0.2 on 2019-11-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_content_reviews_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='reviews_total',
            field=models.IntegerField(default=0),
        ),
    ]
